### ISSUE TITLE
USB gadget mode doesn't work on the OTG port

### ISSUE THREAD

**Issue by fhunleth** [fhunleth/nerves_system_mangopi_mq_pro#8]
Everything looks right on the device side, but there's no USB traffic at all going to the host computer.

Here are some notes:

* Experiments with the 5.14 and 5.18 snapshots of the `smaeul` Linux kernel fork didn't work
* The Armbian images for the MQ Pro didn't work for me. This used the Linux 5.19-rc0 branch of the `smaeul` repository.
* The `YuzukiHD` Buildroot repository DOES work. I can ping the device over the link. However, it kernel panics very easily.

**Comment by spunkedy** [comment]
Do you have any working branches for the alternative buildroot images, or are you testing them directly without nerves attached?

**Comment by fhunleth** [comment]
I tested them without Nerves.

**Comment by fhunleth** [comment]
It works with smaeul's 5.19 and 6.1 branches.
